#!/bin/bash
function asopencode(){
    $HDSHOME"/hdssoft/android-studio/bin/studio.sh" $1
}
function hdsopenvscode(){
    #echo "test:"$1
    if [[ "$1" = "" ]];then        
		oldfilepath=""
		xsel -o -b > $HDSHOME"/hdsjiaohuan/jianqieban_oo_info.txt"
        #下一行相当于添加一个回车
        echo "" >> $HDSHOME"/hdsjiaohuan/jianqieban_oo_info.txt"
        while read line
        do

            if [[ "$line" = "" ]];then        
                # echo "$line"
                continue
            fi


            #二进制文件不支持打开
            strA=$line
            strB="匹配到二进制文件"
            #判断是否包含有“：”
            if [[ $strA =~ $strB ]]            
            then
                echo "$line  不支持打开"
                continue
            fi


            # echo "    line："$line
            strA=$line
            strB=":"
            line_left=""
            hdsfilepath=""
            hdsfileline=""
            #判断是否包含有“：”
            if [[ $strA =~ $strB ]]            
            then
                #下一行是截取：左边的字符串
                line_left=${line%%:*}
                hdsfilepath=$line_left
                # echo "    line："$line

                #考虑打开文件的时候，跳到指定的行
                # line_right=${var#*//}
                # 其中 var 是变量名，# 号是运算符，*// 表示从左边开始删除第一个 // 号及左边的所有字符
                #下一行是截取：右边的字符串
                line_right=${line#*:}
                if [[ "$line" != "" ]];then     
                    #下一行是截取：左边的字符串
                    line_right=${line_right%%:*}   
                    hdsfileline=$line_right
                    # line="$line_left:$line_right"
                fi
            else
                # echo "not line："$line
                echo ""
                hdsfilepath=$line
            fi
            # echo "    hdsfilepath:"$hdsfilepath
            #要判断前一行所指向的文件是否相同
            if [ "$oldfilepath" == "$hdsfilepath" ] ;then
                oldfilepath=$hdsfilepath
                #echo "路径:$line   已打开"
                continue
            fi
            # 判断文件是否存在
            oldfilepath=$hdsfilepath
            if [ -f "$hdsfilepath" ];then
                # echo "路径:$hdsfilepath   存在"
                if [[ "$hdsfileline" == "" ]];then 
                    # history -s "aa $line"
                    asopencode $line
                    echo "$line" | xclip  -selection c
                else
                    # history -s "aa $hdsfilepath:$hdsfileline"
                    # /usr/bin/code --goto "$hdsfilepath:$hdsfileline"
                    asopencode $hdsfilepath
                    echo "$hdsfilepath:$hdsfileline" | xclip  -selection c
                    echo "路径已经复制到剪切板：$hdsfilepath:$hdsfileline"
                    #这里是根据行号来打开文件
                    #使用这个xclip 才能把输出真正的输出到剪切板
                fi
                # 
            else
                # 判断文件夹是否存在    文件夹不在这里打开
                # if [ -d "$line" ];then
                #     echo "路径:$line   存在"
                #     openvscode $line
                # else
                #     echo "路径:$line   不存在"
                # fi

                if [ -d "$hdsfilepath" ];then
                    echo "路径:$hdsfilepath   存在，但文件夹不会被打开"
                fi
            fi

        done < $HDSHOME"/hdsjiaohuan/jianqieban_oo_info.txt"
	else
        asopencode $1
    fi
}
echo "使用方法:o:获取剪切板文字分析打开文件。如果有参数，那参数是filepath。将打开文件 oo:直接打开ff_result_filter.txt列表中的文件，详见o的用法"
hdsopenvscode $1
