#!/bin/bash
echo "adb shell rm -rf /sdcard/mtklog/"
adb shell rm -rf /sdcard/mtklog/
# adb shell am start -n com.mediatek.mtklogger/.MainActivity 
# (start表示开启，stop表示关闭；23可改为1/2/4/16，分别代表MobileLog/ModemLog/NetworkLog/GPSLog)
echo "adb shell am broadcast -a com.mediatek.mtklogger.ADB_CMD -e cmd_name start --ei cmd_target 23"
echo "----------------------------------"
adb shell am broadcast -a com.mediatek.mtklogger.ADB_CMD -e cmd_name start --ei cmd_target 23
# adb shell am broadcast -a com.mediatek.mtklogger.ADB_CMD -e cmd_name start --ei cmd_target 1
